// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuaCaGuv9IMkTmiOyShGcF-HNDLHPHmoA',
    appId: '1:1001328795342:web:f43cf4e8bc096d84633a9f',
    messagingSenderId: '1001328795342',
    projectId: 'gtu-app-3b991',
    authDomain: 'gtu-app-3b991.firebaseapp.com',
    storageBucket: 'gtu-app-3b991.appspot.com',
    measurementId: 'G-F3CRX2QXSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHp0vv6sVbnyTIskm-Wkkc9K2rOrwvD0',
    appId: '1:1001328795342:android:22fc72214fdc5936633a9f',
    messagingSenderId: '1001328795342',
    projectId: 'gtu-app-3b991',
    storageBucket: 'gtu-app-3b991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhOHifveNu0cjSOH8s-YYXc-dc5e-oIU8',
    appId: '1:1001328795342:ios:330a29e2c7f1dda9633a9f',
    messagingSenderId: '1001328795342',
    projectId: 'gtu-app-3b991',
    storageBucket: 'gtu-app-3b991.appspot.com',
    iosClientId: '1001328795342-1ogia4eghv6sgvtols5p980lomgd7aju.apps.googleusercontent.com',
    iosBundleId: 'com.astronapps.gtuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhOHifveNu0cjSOH8s-YYXc-dc5e-oIU8',
    appId: '1:1001328795342:ios:330a29e2c7f1dda9633a9f',
    messagingSenderId: '1001328795342',
    projectId: 'gtu-app-3b991',
    storageBucket: 'gtu-app-3b991.appspot.com',
    iosClientId: '1001328795342-1ogia4eghv6sgvtols5p980lomgd7aju.apps.googleusercontent.com',
    iosBundleId: 'com.astronapps.gtuApp',
  );
}
